# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('titular', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('saldo', models.DecimalField(decimal_places=0, max_digits=10000)),
                ('limite', models.DecimalField(decimal_places=0, max_digits=10000)),
            ],
        ),
    ]
