# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='contatos',
            field=models.ManyToManyField(related_name='_conta_contatos_+', to='contas.Conta'),
        ),
    ]
