# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contas', '0003_conta_contatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='Usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conta', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
