# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_conta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
