# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_remove_conta_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cpf',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
