# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_conta_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='saldo',
            field=models.FloatField(),
        ),
    ]
